version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 140023376730.dkr.ecr.us-west-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $ImageName -f Dockerfile .

  post_build:
    commands:
      - echo "Tagging Docker image"
      - docker tag $ImageName:latest 140023376730.dkr.ecr.us-west-1.amazonaws.com/$ImageName:latest
      - echo "Pushing Docker image"
      - docker push 140023376730.dkr.ecr.us-west-1.amazonaws.com/$ImageName:latest

artifacts:
  files:
    - '**/*'
